name: Deploy JavaScript

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Site
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            git clone -b php git@github.com:sistematico/pagseguro.git /var/www/pagseguro-php.lucasbrum.net
            cd /var/www/pagseguro-php.lucasbrum.net
            git pull